name: CI

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@master

      - name: Restore Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Restore npm Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Lint Project
        shell: bash
        run: npm run lint

      - name: Run Unit Tests
        shell: bash
        run: npm test

      - name: Build Android App Bundle
        run: |
          cd android && chmod +x ./gradlew && ./gradlew bundleRelease --no-daemon
